version: '3.4'

networks:
  services-network:
    driver: bridge 

services:
  Consumer:
    container_name: consumer
    image: consumer:latest
    build:
      context: Consumer
      dockerfile: Dockerfile
    ports:
      - "5051:80"
    networks:
      - services-network
    depends_on:
      RabbitMQ:
        condition: service_healthy

  Producer:
    container_name: producer
    image: producer:latest
    build:
      context: Producer
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    networks:
      - services-network
    depends_on:
      RabbitMQ:
        condition: service_healthy

  RabbitMQ:
    container_name: rabbitmqq
    image: rabbitmq:3-management
    ports:
    - "5672:5672"
    - "15672:15672"
    networks:
    - services-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"] # проверяем статус сервиса RabbitMQ
      interval: 30s # интервал проверки
      timeout: 10s # таймаут проверки
      retries: 5 # количество попыток проверки